FROM python:3.10-slim

WORKDIR /code

RUN apt -y update && apt -y install locales
RUN echo "ja_JP UTF-8" > /etc/locale.gen
RUN locale-gen

COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

